# -*- coding: utf-8 -*-
"""RAG Final project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EQVEOGJ4GF0z3B7kCxe0j8EZ1Uf5uZP6
"""

# STEP 1: Install Libraries
!pip install -q langchain langgraph chromadb pypdf sentence-transformers openai tiktoken langchain-community
!pip install -q -U google-genai

# STEP 2: Upload PDF
from google.colab import files
uploaded = files.upload()

pdf_file = list(uploaded.keys())[0]
print("Uploaded:", pdf_file)

# STEP 3: Imports
# Install latest packages first
!pip install -q -U langchain langchain-community langgraph chromadb pypdf sentence-transformers langchain-openai langchain-text-splitters

# Correct Imports
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

from langchain_openai import ChatOpenAI

from langgraph.graph import StateGraph, END
from typing import TypedDict
import os

# STEP 4: Add OpenAI Key

from google import genai

client = genai.Client(api_key="AIzaSyBwk8L4d3BsT7r5XMVfLgh0eFtbuyK5JQQ")

# STEP 5: Load PDF
loader = PyPDFLoader(pdf_file)
docs = loader.load()

print("Pages Loaded:", len(docs))

# STEP 6: Split into Chunks
splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)
chunks = splitter.split_documents(docs)
print("Chunks Created:", len(chunks))

# STEP 7: Create Embeddings
embedding = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# STEP 8: Store in ChromaDB
vectordb = Chroma.from_documents(
    documents=chunks,
    embedding=embedding
)

retriever = vectordb.as_retriever(search_kwargs={"k":3})

print("Vector DB Ready")

# STEP 10: LangGraph State
class GraphState(TypedDict):
    question: str
    context: str
    answer: str
    route: str

# STEP 11: Process Query Node

def process_query(state):
    question = state["question"]

    docs = retriever.invoke(question)

    context = "\n".join([doc.page_content for doc in docs])

    if len(context) < 100:
        route = "human"
    else:
        route = "ai"

    return {
        "question": question,
        "context": context,
        "route": route
    }

# STEP 12: AI Answer Node
def generate_answer(state):
    prompt = f"""
You are customer support assistant.

Use this context to answer:

{state['context']}

Question:
{state['question']}
"""

    response = llm.invoke(prompt)

    return {
        "answer": response.content
    }

# STEP 13: Human Escalation Node
def human_support(state):
    return {
        "answer": "⚠️ This query requires human support assistance."
    }

# STEP 14: Conditional Routing
def route_decision(state):
    return state["route"]

# STEP 15: Build LangGraph
workflow = StateGraph(GraphState)

workflow.add_node("process", process_query)
workflow.add_node("ai_answer", generate_answer)
workflow.add_node("human", human_support)

workflow.set_entry_point("process")

workflow.add_conditional_edges(
    "process",
    route_decision,
    {        "ai": "ai_answer",
        "human": "human"
    }
)

workflow.add_edge("ai_answer", END)
workflow.add_edge("human", END)

app = workflow.compile()

print("LangGraph Ready")

from google.colab import files

uploaded = files.upload()

pdf_file = list(uploaded.keys())[0]
print("Uploaded File:", pdf_file)

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

from langgraph.graph import StateGraph, END
from typing import TypedDict

import google.generativeai as genai
import os

loader = PyPDFLoader(pdf_file)
docs = loader.load()

print("Pages Loaded:", len(docs))

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)

chunks = splitter.split_documents(docs)

print("Chunks Created:", len(chunks))

embedding = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vectordb = Chroma.from_documents(
    documents=chunks,
    embedding=embedding
)

retriever = vectordb.as_retriever(search_kwargs={"k": 3})

print("Vector DB Ready")

model = genai.GenerativeModel("gemini-2.0-flash")

class GraphState(TypedDict):
    question: str
    context: str
    answer: str
    route: str

def process_query(state):
    question = state["question"]

    docs = retriever.invoke(question)

    context = "\n".join([doc.page_content for doc in docs])

    if len(context) < 100:
        route = "human"
    else:
        route = "ai"

    return {
        "question": question,
        "context": context,
        "route": route
    }

# STEP 12: FREE No API Answer Node

def generate_answer(state):
    context = state["context"].strip()

    if context:
        return {
            "answer": context[:1200]
        }
    else:
        return {
            "answer": "No relevant information found in the document."
        }

def human_support(state):
    return {
        "answer": "⚠️ This query requires human support assistance."
    }

def route_decision(state):
    return state["route"]

workflow = StateGraph(GraphState)

workflow.add_node("process", process_query)
workflow.add_node("ai_answer", generate_answer)
workflow.add_node("human", human_support)

workflow.set_entry_point("process")

workflow.add_conditional_edges(
    "process",
    route_decision,
    {
        "ai": "ai_answer",
        "human": "human"
    }
)

workflow.add_edge("ai_answer", END)
workflow.add_edge("human", END)

app = workflow.compile()

print("LangGraph Ready")

while True:
    q = input("\nAsk Question (type exit): ")

    if q.lower() == "exit":
        print("Chat Ended")
        break

    try:
        result = app.invoke({"question": q})
        print("\nAnswer:\n", result["answer"])

    except Exception as e:
        print("\nError:", e)

